export default [
//     {
//     id: 3,
//     name: '供采协同',
//     path: '/trading',
//     component: Layout,
//     redirect: '/trading/order',
//     pid: -1,
//     description: '一级目录',
//     type: 1,
//     sort: 1,
//     icon: 'icon-icon-Order',
//     children: [
//       {
//         id: 6,
//         name: '订单',
//         path: '/trading/order',
//         component: $import('/trading/order'),
//         pid: 3,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//       {
//         id: 12,
//         name: '送货单',
//         path: '/trading/delivery',
//         component: $import('/trading/delivery'),
//         pid: 3,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//     ],
//   },
//   {
//     id: 15,
//     name: '证件管理',
//     path: '/credential',
//     pid: -1,
//     description: '一级目录',
//     type: 1,
//     sort: 1,
//     icon: 'icon-icon-Certificates',
//     children: [
//       {
//         id: 18,
//         name: '证件绑定及推送',
//         path: '/credential/bindingAndPush',
//         pid: 15,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//       {
//         id: 21,
//         name: '我的证件',
//         path: '/credential/mycred',
//         pid: 15,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//       {
//         id: 24,
//         name: '厂商及材料证件',
//         path: '/credential/producercred',
//         pid: 15,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//       {
//         id: 27,
//         name: '代理商证件',
//         path: '/credential/agentcred',
//         pid: 15,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//     ],
//   },
//   {
//     id: 30,
//     name: '医院管理',
//     path: '/hospital',
//     component: Layout,
//     pid: -1,
//     description: '一级目录',
//     type: 1,
//     sort: 1,
//     icon: 'icon-icon-hospital',
//     children: [
//       {
//         id: 33,
//         name: '医院列表',
//         path: 'hospital/list',
//         component: $import('Hospital/index'),
//         pid: 30,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//     ],
//   },
//   {

//     id: 42,
//     name: '系统设置',
//     path: '/account',
//     pid: -1,
//     description: '一级目录',
//     type: 1,
//     sort: 1,
//     icon: 'icon-icon-setup-fill',
//     children: [
//       {
//         id: 45,
//         name: '用户管理',
//         path: '/account/user',
//         pid: 42,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//       {
//         id: 48,
//         name: '角色管理',
//         path: '/account/role',
//         pid: 42,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//       {
//         id: 51,
//         name: '企业管理',
//         path: '/account/enterprise',
//         pid: 42,
//         description: '二级目录',
//         type: 1,
//         sort: 1,
//         icon: '',
//         children: [],
//       },
//     ],
//   },
];
